# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Behavior_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Behavior_iOS
 pod 'pop','~>1.0.6'
 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'ReactiveCocoa', '~> 2.5'
 pod 'Masonry', '~> 0.6.1'
end
